apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devhub
  namespace: argocd
spec:
  description: Plateforme DevHub Campus SRE (TP 3)

  sourceRepos:
    - https://github.com/valaack/pulse-campus.git
    - https://argoproj.github.io/argo-helm
    - https://prometheus-community.github.io/helm-charts

  destinations:
    - server: https://kubernetes.default.svc
      namespace: devhub-*
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: argo-rollouts
    - server: https://kubernetes.default.svc
      namespace: argocd

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: policy
      kind: PodSecurityPolicy
    - group: monitoring.coreos.com
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
