apiVersion: v2
name: annuaire
description: Chart Helm du service annuaire — DevHub Campus SRE (TP 3)
type: application
version: 0.2.0
appVersion: "0.2.0"
# Déclarez-vous comme maintainer dès que vous forkez.
# maintainers:
#   - name: Prénom Nom
#     email: prenom.nom@example.com
