{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "annuaire.fullname" . }}
  labels:
    {{- include "annuaire.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.serviceMonitor.release | quote }}
spec:
  selector:
    matchLabels:
      {{- include "annuaire.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
